version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:8000"
    volumes:
      - data-volume:/app/data
    environment:
      - GIPHY_API_TOKEN=${GIPHY_API_TOKEN}
volumes:
  data-volume:
