"""added audit column for categories

Revision ID: 25858de709e5
Revises: 304d6ba3c795
Create Date: 2024-06-09 17:51:44.210576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25858de709e5'
down_revision = '304d6ba3c795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated_by', sa.String(length=130), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('last_updated_by')

    # ### end Alembic commands ###
