"""Added audit column

Revision ID: 2f5a4e907518
Revises: 61fac01b7ce5
Create Date: 2024-06-03 15:31:50.865299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5a4e907518'
down_revision = '61fac01b7ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated_by', sa.String(length=130), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_column('last_updated_by')

    # ### end Alembic commands ###
