"""Add last shown attribute to quotes

Revision ID: 8d322bf4e7e8
Revises: 1a8bbf732309
Create Date: 2025-05-26 10:59:45.830130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d322bf4e7e8'
down_revision = '1a8bbf732309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_shown', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_quote_last_shown'), ['last_shown'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_last_shown'))
        batch_op.drop_column('last_shown')

    # ### end Alembic commands ###
