"""Added audit column

Revision ID: f0c496637ec3
Revises: 
Create Date: 2024-06-01 14:16:01.056635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c496637ec3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        if not column_exists('entry', 'last_updated_by'):  # Add this check
            batch_op.add_column(sa.Column('last_updated_by', sa.String(length=130), nullable=True))
    # ### end Alembic commands ###

def column_exists(table_name, column_name):
    engine = op.get_bind()
    inspector = sa.inspect(engine)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_column('last_updated_by')

    # ### end Alembic commands ###
